[package]
name = "shutdown"
version = "0.1.0"
authors = ["Andreas Rammhold <andreas@rammhold.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqtt = "0.31.0"
mqtt311 = "0.2.0"
tokio = "0.1"
futures = "0.1.29"
